name: onboarding_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  beamer: ^1.5.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.16
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  injectable: ^2.0.1
  percent_indicator: ^4.2.2

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.8
  injectable_generator: ^2.0.1
  freezed: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#292A2A"
  image: "assets/images/launcher_image.png"
